#include <cuda.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define CUDA_CHECK(x) do { CUresult _r = (x); if (_r != CUDA_SUCCESS) { const char* _s; cuGetErrorString(_r, &_s); fprintf(stderr, "CUDA error at %s:%d: %s\n", __FILE__, __LINE__, _s); } } while(0)

static const char* ptx_gpu = 
    "//\n"
    "// Generated by LLVM NVPTX Back-End\n"
    "//\n"
    "\n"
    ".version 7.1\n"
    ".target sm_86\n"
    ".address_size 64\n"
    "\n"
    "	// .globl	addArrays\n"
    "\n"
    ".visible .entry addArrays(\n"
    "	.param .u64 .ptr .align 1 addArrays_param_0,\n"
    "	.param .u64 .ptr .align 1 addArrays_param_1,\n"
    "	.param .u64 .ptr .align 1 addArrays_param_2\n"
    ")\n"
    "{\n"
    "	.reg .b32 	%r<5>;\n"
    "	.reg .b64 	%rd<11>;\n"
    "\n"
    "	ld.param.b64 	%rd1, [addArrays_param_0];\n"
    "	cvta.to.global.u64 	%rd2, %rd1;\n"
    "	ld.param.b64 	%rd3, [addArrays_param_1];\n"
    "	cvta.to.global.u64 	%rd4, %rd3;\n"
    "	ld.param.b64 	%rd5, [addArrays_param_2];\n"
    "	cvta.to.global.u64 	%rd6, %rd5;\n"
    "	mov.u32 	%r1, %tid.x;\n"
    "	mul.wide.u32 	%rd7, %r1, 4;\n"
    "	add.s64 	%rd8, %rd2, %rd7;\n"
    "	ld.global.b32 	%r2, [%rd8];\n"
    "	add.s64 	%rd9, %rd4, %rd7;\n"
    "	ld.global.b32 	%r3, [%rd9];\n"
    "	add.rn.f32 	%r4, %r2, %r3;\n"
    "	add.s64 	%rd10, %rd6, %rd7;\n"
    "	st.global.b32 	[%rd10], %r4;\n"
    "	ret;\n"
    "\n"
    "}\n"
;

static CUmodule tec_gpu_module_gpu;
static CUfunction tec_gpu_kernel_gpu_addArrays;

void tec_gpu_init_gpu() {
    CUdevice device;
    CUcontext ctx;
    CUDA_CHECK(cuInit(0));
    CUDA_CHECK(cuDeviceGet(&device, 0));
    CUDA_CHECK(cuDevicePrimaryCtxRetain(&ctx, device));
    CUDA_CHECK(cuCtxSetCurrent(ctx));
    CUDA_CHECK(cuModuleLoadData(&tec_gpu_module_gpu, ptx_gpu));
    CUDA_CHECK(cuModuleGetFunction(&tec_gpu_kernel_gpu_addArrays, tec_gpu_module_gpu, "addArrays"));
}

float* gpu_addArrays(float* a, int a_size, float* b, int b_size) {
    CUdeviceptr d_a;
    CUDA_CHECK(cuMemAlloc(&d_a, a_size * sizeof(float)));
    CUDA_CHECK(cuMemcpyHtoD(d_a, a, a_size * sizeof(float)));
    CUdeviceptr d_b;
    CUDA_CHECK(cuMemAlloc(&d_b, b_size * sizeof(float)));
    CUDA_CHECK(cuMemcpyHtoD(d_b, b, b_size * sizeof(float)));
    CUdeviceptr d_result;
    CUDA_CHECK(cuMemAlloc(&d_result, a_size * sizeof(float)));
    void* args[] = {&d_a, &d_b, &d_result};
    CUDA_CHECK(cuLaunchKernel(tec_gpu_kernel_gpu_addArrays,
        1, 1, 1,
        a_size, 1, 1,
        0, 0, args, 0));
    CUDA_CHECK(cuCtxSynchronize());

    float* result = (float*)malloc(a_size * sizeof(float));
    CUDA_CHECK(cuMemcpyDtoH(result, d_result, a_size * sizeof(float)));
    CUDA_CHECK(cuMemFree(d_a));
    CUDA_CHECK(cuMemFree(d_b));
    cuMemFree(d_result);
    return result;
}

