#include <cuda.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define CUDA_CHECK(x) do { CUresult _r = (x); if (_r != CUDA_SUCCESS) { const char* _s; cuGetErrorString(_r, &_s); fprintf(stderr, "CUDA error at %s:%d: %s\n", __FILE__, __LINE__, _s); } } while(0)

static const char* ptx_gpu = 
    "//\n"
    "// Generated by LLVM NVPTX Back-End\n"
    "//\n"
    "\n"
    ".version 7.1\n"
    ".target sm_86\n"
    ".address_size 64\n"
    "\n"
    "	// .globl	sumReduce\n"
    "// tile has been demoted\n"
    "\n"
    ".visible .entry sumReduce(\n"
    "	.param .u64 .ptr .align 1 sumReduce_param_0,\n"
    "	.param .u32 sumReduce_param_1,\n"
    "	.param .u64 .ptr .align 1 sumReduce_param_2\n"
    ")\n"
    "{\n"
    "	.reg .pred 	%p<5>;\n"
    "	.reg .b32 	%r<21>;\n"
    "	.reg .b64 	%rd<19>;\n"
    "	// demoted variable\n"
    "	.shared .align 4 .b8 tile[1024];\n"
    "	ld.param.b64 	%rd5, [sumReduce_param_0];\n"
    "	cvta.to.global.u64 	%rd1, %rd5;\n"
    "	ld.param.b32 	%r7, [sumReduce_param_1];\n"
    "	ld.param.b64 	%rd6, [sumReduce_param_2];\n"
    "	cvta.to.global.u64 	%rd2, %rd6;\n"
    "	mov.u32 	%r1, %tid.x;\n"
    "	mov.u32 	%r8, %ctaid.x;\n"
    "	mov.u32 	%r2, %ntid.x;\n"
    "	mad.lo.s32 	%r3, %r8, %r2, %r1;\n"
    "	setp.ge.s32 	%p1, %r3, %r7;\n"
    "	mul.wide.u32 	%rd18, %r1, 4;\n"
    "	@%p1 bra 	$L__BB0_2;\n"
    "	mul.wide.s32 	%rd10, %r3, 4;\n"
    "	add.s64 	%rd11, %rd1, %rd10;\n"
    "	ld.global.b32 	%r9, [%rd11];\n"
    "	mov.b64 	%rd13, tile;\n"
    "	add.s64 	%rd14, %rd13, %rd18;\n"
    "	st.shared.b32 	[%rd14], %r9;\n"
    "	bra.uni 	$L__BB0_3;\n"
    "$L__BB0_2:\n"
    "	mov.b64 	%rd8, tile;\n"
    "	add.s64 	%rd9, %rd8, %rd18;\n"
    "	st.shared.b32 	[%rd9], 0;\n"
    "$L__BB0_3:\n"
    "	bar.sync 	0;\n"
    "	shr.u32 	%r10, %r2, 31;\n"
    "	add.s32 	%r11, %r2, %r10;\n"
    "	shr.s32 	%r20, %r11, 1;\n"
    "	bra.uni 	$L__BB0_4;\n"
    "$L__BB0_7:\n"
    "	bar.sync 	0;\n"
    "	shr.u32 	%r18, %r20, 31;\n"
    "	add.s32 	%r19, %r20, %r18;\n"
    "	shr.s32 	%r20, %r19, 1;\n"
    "$L__BB0_4:\n"
    "	setp.lt.s32 	%p2, %r20, 1;\n"
    "	@%p2 bra 	$L__BB0_8;\n"
    "	setp.lt.s32 	%p4, %r1, %r20;\n"
    "	@%p4 bra 	$L__BB0_6;\n"
    "	bra.uni 	$L__BB0_7;\n"
    "$L__BB0_6:\n"
    "	add.s32 	%r14, %r1, %r20;\n"
    "	mul.wide.s32 	%rd15, %r14, 4;\n"
    "	mov.b64 	%rd16, tile;\n"
    "	add.s64 	%rd3, %rd16, %rd15;\n"
    "	add.s64 	%rd4, %rd16, %rd18;\n"
    "	ld.shared.b32 	%r15, [%rd3];\n"
    "	ld.shared.b32 	%r16, [%rd4];\n"
    "	add.s32 	%r17, %r16, %r15;\n"
    "	st.shared.b32 	[%rd4], %r17;\n"
    "	bra.uni 	$L__BB0_7;\n"
    "$L__BB0_8:\n"
    "	setp.eq.b32 	%p3, %r1, 0;\n"
    "	@%p3 bra 	$L__BB0_9;\n"
    "	bra.uni 	$L__BB0_10;\n"
    "$L__BB0_9:\n"
    "	ld.shared.b32 	%r12, [tile];\n"
    "	atom.global.add.u32 	%r13, [%rd2], %r12;\n"
    "$L__BB0_10:\n"
    "	ret;\n"
    "\n"
    "}\n"
;

static CUmodule tec_gpu_module_gpu;
static CUfunction tec_gpu_kernel_gpu_sumReduce;

void tec_gpu_init_gpu() {
    CUdevice device;
    CUcontext ctx;
    CUDA_CHECK(cuInit(0));
    CUDA_CHECK(cuDeviceGet(&device, 0));
    CUDA_CHECK(cuDevicePrimaryCtxRetain(&ctx, device));
    CUDA_CHECK(cuCtxSetCurrent(ctx));
    CUDA_CHECK(cuModuleLoadData(&tec_gpu_module_gpu, ptx_gpu));
    CUDA_CHECK(cuModuleGetFunction(&tec_gpu_kernel_gpu_sumReduce, tec_gpu_module_gpu, "sumReduce"));
}

void* gpu_sumReduce(int* data, int data_size, int size, int* result, int result_size) {
    CUdeviceptr d_data;
    CUDA_CHECK(cuMemAlloc(&d_data, data_size * sizeof(int)));
    CUDA_CHECK(cuMemcpyHtoD(d_data, data, data_size * sizeof(int)));
    CUdeviceptr d_result;
    CUDA_CHECK(cuMemAlloc(&d_result, result_size * sizeof(int)));
    CUDA_CHECK(cuMemcpyHtoD(d_result, result, result_size * sizeof(int)));
    void* args[] = {&d_data, &size, &d_result, };
    int threadsPerBlock = 1;
    while (threadsPerBlock < data_size && threadsPerBlock < 256) threadsPerBlock *= 2;
    int numBlocks = (data_size + threadsPerBlock - 1) / threadsPerBlock;
    CUDA_CHECK(cuLaunchKernel(tec_gpu_kernel_gpu_sumReduce,
        numBlocks, 1, 1,
        threadsPerBlock, 1, 1,
        0, 0, args, 0));
    CUDA_CHECK(cuCtxSynchronize());

    cuMemcpyDtoH(data, d_data, data_size * sizeof(int));
    cuMemcpyDtoH(result, d_result, result_size * sizeof(int));
    CUDA_CHECK(cuMemFree(d_data));
    CUDA_CHECK(cuMemFree(d_result));
}

